### ISSUE TITLE
How to scale up to big data?

### ISSUE THREAD

**Issue by parhamouni** [xptree/NetMF#4]
Thanks for the great paper. I would like to use it on a specific application with big data, yet it fails in the middle of the computations due to memory issues. Do you have any suggestions on how to improve the code to be applicable to adjacency matrices of million nodes?

**Comment by xptree** [comment]
@parhamouni Hi, you may want to try our recent work NetSMF[[paper]](https://arxiv.org/abs/1906.11156)[[code]](https://github.com/xptree/NetSMF), which extend NetMF to large-scale networks. Thanks!

**Comment by parhamouni** [comment]
Definitely would take a look at it, thank you!
