### ISSUE TITLE
reason for returning S_d \sqrt(\Sigma_d) as the network embedding

### ISSUE THREAD

**Issue by iverson333** [xptree/NetMF#9]
Thanks for sharing the code. I'm curious about why after obtaining the approximated deepwalk matrix (after max(x, 1) and taking log), in the last step of NetMF,  it is $$U_d \sqrt(\Sigma_d)$$ from SVD that is returned as the final embedding? The paper doesn't seem to justify the benefit of this instead of some other embedding.

**Comment by xptree** [comment]
Yes, there are other choices.

We mainly follow Levy and Goldberg (https://papers.nips.cc/paper/2014/file/feab05aa91085b7a8012516bc3533958-Paper.pdf) to use $U_d \sqrt(\Sigma_d)$. See their Eq.13.
